<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsuariosRolesSeeder extends Seeder
{
    /**
     * Crea usuarios de prueba para validar acceso por rol.
     */
    public function run(): void
    {
        $fechaHoy = now()->toDateString();

        $usuarios = [
            [
                'email' => 'empleado@sistema.local',
                'name' => 'empleado_demo',
                'nombre_usuario' => 'empleado_demo',
                'password' => 'Empleado123!',
                'nombre' => 'Erika',
                'apellido_paterno' => 'Molina',
                'apellido_materno' => 'Perez',
                'curp' => 'GODL920303MDFMZS03',
                'telefono_contacto_1' => '5551000001',
                'telefono_contacto_2' => '5551000101',
                'area_contratacion' => 'Operaciones',
                'numero_seguro_social' => 'NSS9203030003',
                'direccion' => 'Calle Uno 100',
                'colonia' => 'Centro',
                'codigo_postal' => '01010',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'EMPLEADO',
            ],
            [
                'email' => 'vendedor@sistema.local',
                'name' => 'vendedor_demo',
                'nombre_usuario' => 'vendedor_demo',
                'password' => 'Vendedor123!',
                'nombre' => 'Victor',
                'apellido_paterno' => 'Reyes',
                'apellido_materno' => 'Lozano',
                'curp' => 'HEPJ930404HDFRZG04',
                'telefono_contacto_1' => '5551000002',
                'telefono_contacto_2' => '5551000102',
                'area_contratacion' => 'Ventas',
                'numero_seguro_social' => 'NSS9304040004',
                'direccion' => 'Calle Dos 200',
                'colonia' => 'Del Valle',
                'codigo_postal' => '03100',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'VENDEDOR',
            ],
            [
                'email' => 'supervisor@sistema.local',
                'name' => 'supervisor_demo',
                'nombre_usuario' => 'supervisor_demo',
                'password' => 'Supervisor123!',
                'nombre' => 'Sofia',
                'apellido_paterno' => 'Ramirez',
                'apellido_materno' => 'Nava',
                'curp' => 'RANS880303MDFKRL03',
                'telefono_contacto_1' => '5551000003',
                'telefono_contacto_2' => '5551000103',
                'area_contratacion' => 'Operaciones',
                'numero_seguro_social' => 'NSS8803030003',
                'direccion' => 'Calle Tres 300',
                'colonia' => 'Roma Norte',
                'codigo_postal' => '06700',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'SUPERVISOR',
            ],
            [
                'email' => 'supervisor.rh@sistema.local',
                'name' => 'supervisor_rh',
                'nombre_usuario' => 'supervisor_rh',
                'password' => 'Supervisor123!',
                'nombre' => 'Rocio',
                'apellido_paterno' => 'Mejia',
                'apellido_materno' => 'Castillo',
                'curp' => 'MECR890101MDFHSL11',
                'telefono_contacto_1' => '5551000011',
                'telefono_contacto_2' => '5551000111',
                'area_contratacion' => 'Recursos Humanos',
                'numero_seguro_social' => 'NSS8901010011',
                'direccion' => 'Calle Siete 700',
                'colonia' => 'Escandon',
                'codigo_postal' => '11800',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'SUPERVISOR',
            ],
            [
                'email' => 'supervisor.finanzas@sistema.local',
                'name' => 'supervisor_finanzas',
                'nombre_usuario' => 'supervisor_finanzas',
                'password' => 'Supervisor123!',
                'nombre' => 'Fernando',
                'apellido_paterno' => 'Prieto',
                'apellido_materno' => 'Mata',
                'curp' => 'PIMF900202HDFRNN12',
                'telefono_contacto_1' => '5551000012',
                'telefono_contacto_2' => '5551000112',
                'area_contratacion' => 'Finanzas',
                'numero_seguro_social' => 'NSS9002020012',
                'direccion' => 'Calle Ocho 800',
                'colonia' => 'Anzures',
                'codigo_postal' => '11590',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'SUPERVISOR',
            ],
            [
                'email' => 'supervisor.ventas@sistema.local',
                'name' => 'supervisor_ventas',
                'nombre_usuario' => 'supervisor_ventas',
                'password' => 'Supervisor123!',
                'nombre' => 'Vanessa',
                'apellido_paterno' => 'Lugo',
                'apellido_materno' => 'Rios',
                'curp' => 'LURV910303MDFTNS13',
                'telefono_contacto_1' => '5551000013',
                'telefono_contacto_2' => '5551000113',
                'area_contratacion' => 'Ventas',
                'numero_seguro_social' => 'NSS9103030013',
                'direccion' => 'Calle Nueve 900',
                'colonia' => 'Doctores',
                'codigo_postal' => '06720',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'SUPERVISOR',
            ],
            [
                'email' => 'supervisor.tecnologia@sistema.local',
                'name' => 'supervisor_tecnologia',
                'nombre_usuario' => 'supervisor_tecnologia',
                'password' => 'Supervisor123!',
                'nombre' => 'Tania',
                'apellido_paterno' => 'Solis',
                'apellido_materno' => 'Rangel',
                'curp' => 'SORT920404MDFLNL14',
                'telefono_contacto_1' => '5551000014',
                'telefono_contacto_2' => '5551000114',
                'area_contratacion' => 'Tecnologia',
                'numero_seguro_social' => 'NSS9204040014',
                'direccion' => 'Calle Diez 1000',
                'colonia' => 'Noche Buena',
                'codigo_postal' => '03720',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'SUPERVISOR',
            ],
            [
                'email' => 'jefe.area@sistema.local',
                'name' => 'jefe_area_demo',
                'nombre_usuario' => 'jefe_area_demo',
                'password' => 'JefeArea123!',
                'nombre' => 'Javier',
                'apellido_paterno' => 'Torres',
                'apellido_materno' => 'Salas',
                'curp' => 'TOSJ890404HDFPRD04',
                'telefono_contacto_1' => '5551000004',
                'telefono_contacto_2' => '5551000104',
                'area_contratacion' => 'Direccion',
                'numero_seguro_social' => 'NSS8904040004',
                'direccion' => 'Calle Cuatro 400',
                'colonia' => 'Napoles',
                'codigo_postal' => '03810',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'JEFE_AREA',
            ],
            [
                'email' => 'jefe.rh@sistema.local',
                'name' => 'jefe_rh',
                'nombre_usuario' => 'jefe_rh',
                'password' => 'JefeArea123!',
                'nombre' => 'Julio',
                'apellido_paterno' => 'Mora',
                'apellido_materno' => 'Nieto',
                'curp' => 'MONJ900505HDFRHS21',
                'telefono_contacto_1' => '5551000021',
                'telefono_contacto_2' => '5551000121',
                'area_contratacion' => 'Recursos Humanos',
                'numero_seguro_social' => 'NSS9005050021',
                'direccion' => 'Calle RH 210',
                'colonia' => 'Centro',
                'codigo_postal' => '01010',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'JEFE_AREA',
            ],
            [
                'email' => 'jefe.finanzas@sistema.local',
                'name' => 'jefe_finanzas',
                'nombre_usuario' => 'jefe_finanzas',
                'password' => 'JefeArea123!',
                'nombre' => 'Felipe',
                'apellido_paterno' => 'Soria',
                'apellido_materno' => 'Quintana',
                'curp' => 'SOQF910606HDFNNS22',
                'telefono_contacto_1' => '5551000022',
                'telefono_contacto_2' => '5551000122',
                'area_contratacion' => 'Finanzas',
                'numero_seguro_social' => 'NSS9106060022',
                'direccion' => 'Calle FIN 220',
                'colonia' => 'Centro',
                'codigo_postal' => '01010',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'JEFE_AREA',
            ],
            [
                'email' => 'jefe.operaciones@sistema.local',
                'name' => 'jefe_operaciones',
                'nombre_usuario' => 'jefe_operaciones',
                'password' => 'JefeArea123!',
                'nombre' => 'Oscar',
                'apellido_paterno' => 'Beltran',
                'apellido_materno' => 'Iriarte',
                'curp' => 'BEIO920707HDFPRS23',
                'telefono_contacto_1' => '5551000023',
                'telefono_contacto_2' => '5551000123',
                'area_contratacion' => 'Operaciones',
                'numero_seguro_social' => 'NSS9207070023',
                'direccion' => 'Calle OPS 230',
                'colonia' => 'Centro',
                'codigo_postal' => '01010',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'JEFE_AREA',
            ],
            [
                'email' => 'jefe.ventas@sistema.local',
                'name' => 'jefe_ventas',
                'nombre_usuario' => 'jefe_ventas',
                'password' => 'JefeArea123!',
                'nombre' => 'Viviana',
                'apellido_paterno' => 'Campos',
                'apellido_materno' => 'Ruvalcaba',
                'curp' => 'CARV930808MDFVTS24',
                'telefono_contacto_1' => '5551000024',
                'telefono_contacto_2' => '5551000124',
                'area_contratacion' => 'Ventas',
                'numero_seguro_social' => 'NSS9308080024',
                'direccion' => 'Calle VEN 240',
                'colonia' => 'Centro',
                'codigo_postal' => '01010',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'JEFE_AREA',
            ],
            [
                'email' => 'jefe.tecnologia@sistema.local',
                'name' => 'jefe_tecnologia',
                'nombre_usuario' => 'jefe_tecnologia',
                'password' => 'JefeArea123!',
                'nombre' => 'Teresa',
                'apellido_paterno' => 'Navarro',
                'apellido_materno' => 'Linares',
                'curp' => 'NALT940909MDFTCN25',
                'telefono_contacto_1' => '5551000025',
                'telefono_contacto_2' => '5551000125',
                'area_contratacion' => 'Tecnologia',
                'numero_seguro_social' => 'NSS9409090025',
                'direccion' => 'Calle TEC 250',
                'colonia' => 'Centro',
                'codigo_postal' => '01010',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'JEFE_AREA',
            ],
            [
                'email' => 'contador@sistema.local',
                'name' => 'contador_demo',
                'nombre_usuario' => 'contador_demo',
                'password' => 'Contador123!',
                'nombre' => 'Claudia',
                'apellido_paterno' => 'Fuentes',
                'apellido_materno' => 'Lara',
                'curp' => 'LORA900101MDFPRN01',
                'telefono_contacto_1' => '5551000005',
                'telefono_contacto_2' => '5551000105',
                'area_contratacion' => 'Finanzas',
                'numero_seguro_social' => 'NSS9001010001',
                'direccion' => 'Calle Cinco 500',
                'colonia' => 'Condesa',
                'codigo_postal' => '06140',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'CONTADOR',
            ],
            [
                'email' => 'secretaria@sistema.local',
                'name' => 'secretaria_demo',
                'nombre_usuario' => 'secretaria_demo',
                'password' => 'Secretaria123!',
                'nombre' => 'Sandra',
                'apellido_paterno' => 'Ibarra',
                'apellido_materno' => 'Cruz',
                'curp' => 'ICRS910606MDFVLL06',
                'telefono_contacto_1' => '5551000006',
                'telefono_contacto_2' => '5551000106',
                'area_contratacion' => 'Administracion',
                'numero_seguro_social' => 'NSS9106060006',
                'direccion' => 'Calle Seis 600',
                'colonia' => 'Juarez',
                'codigo_postal' => '06600',
                'ciudad' => 'Ciudad de Mexico',
                'estado' => 'CDMX',
                'rol' => 'SECRETARIA',
            ],
        ];

        foreach ($usuarios as $usuario) {
            User::updateOrCreate(
                ['email' => $usuario['email']],
                [
                    'name' => $usuario['name'],
                    'nombre_usuario' => $usuario['nombre_usuario'],
                    'password' => Hash::make($usuario['password']),
                    'nombre' => $usuario['nombre'],
                    'apellido_paterno' => $usuario['apellido_paterno'],
                    'apellido_materno' => $usuario['apellido_materno'],
                    'curp' => $usuario['curp'],
                    'telefono_contacto_1' => $usuario['telefono_contacto_1'],
                    'telefono_contacto_2' => $usuario['telefono_contacto_2'],
                    'fecha_contratacion' => $fechaHoy,
                    'area_contratacion' => $usuario['area_contratacion'],
                    'numero_seguro_social' => $usuario['numero_seguro_social'],
                    'fecha_alta_servicio_salud' => $fechaHoy,
                    'direccion' => $usuario['direccion'],
                    'colonia' => $usuario['colonia'],
                    'codigo_postal' => $usuario['codigo_postal'],
                    'ciudad' => $usuario['ciudad'],
                    'estado' => $usuario['estado'],
                    'rol' => $usuario['rol'],
                    'activo' => true,
                ]
            );
        }
    }
}
